USE `slatt_fashion`;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `phoneNumber` VARCHAR(50) NOT NULL UNIQUE,
  `fullName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('customer','admin') NOT NULL DEFAULT 'customer',
  `address` VARCHAR(255) DEFAULT '',
  `lastLogin` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `isVerified` TINYINT(1) DEFAULT 0,
  `resetPasswordToken` VARCHAR(255),
  `resetPasswordExpiresAt` DATETIME,
  `verificationToken` VARCHAR(255),
  `verificationTokenExpiresAt` DATETIME,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `description` TEXT,
  `category` VARCHAR(255),
  `imageURL` VARCHAR(255),
  `price` FLOAT NOT NULL,
  `available` TINYINT(1) DEFAULT 1,
  `stock` INT DEFAULT 0,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT,
  `orderDescription` VARCHAR(255),
  `amount` FLOAT NOT NULL,
  `orderStatus` ENUM('pending','placed','shipped','delivered') NOT NULL,
  `address` VARCHAR(255) DEFAULT '',
  `totalAmount` FLOAT,
  `discount` FLOAT,
  `trackingId` VARCHAR(255) UNIQUE,
  `placedTime` DATETIME,
  `totalQuantity` INT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cart_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `price` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `userId` INT,
  `productId` INT,
  `orderId` INT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;
